name: Build RISC-V 32-bit Cross-Compilation Packages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-riscv64-linux-gnu \
          g++-riscv64-linux-gnu \
          binutils-riscv64-linux-gnu \
          build-essential \
          cmake \
          wget \
          gawk \
          bison \
          flex \
          texinfo \
          python3 \
          libgmp-dev \
          libmpfr-dev \
          libmpc-dev \
          libisl-dev

    - name: Display toolchain info
      run: |
        riscv64-linux-gnu-gcc --version
        cmake --version

    - name: Build all packages
      run: |
        chmod +x scripts/*.sh
        bash scripts/build-all.sh

    - name: List generated packages
      run: |
        ls -lh build/*.deb

    - name: Upload packages as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: riscv32-cross-packages
        path: build/*.deb
        retention-days: 90

    - name: Create package list
      if: github.event_name == 'release'
      run: |
        cd build
        sha256sum *.deb > SHA256SUMS
        cat SHA256SUMS

    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/*.deb
          build/SHA256SUMS
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
