name: Build RISC-V 32-bit Cross-Compilation Packages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        # Enable deb-src repositories for apt-get source (DEB822 format in Ubuntu 24.04)
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          wget \
          gawk \
          bison \
          flex \
          texinfo \
          python3 \
          autoconf \
          automake \
          libtool \
          pkg-config

    - name: Setup official RISC-V 32-bit toolchain
      run: |
        bash scripts/setup-toolchain.sh
        echo "/opt/riscv32/bin" >> $GITHUB_PATH

    - name: Display toolchain info
      run: |
        riscv32-linux-gnu-gcc --version
        cmake --version

    - name: Make scripts executable
      run: chmod +x scripts/*.sh

    - name: Create build directory
      run: mkdir -p build

    - name: Build linux-libc-dev
      run: |
        bash scripts/build-linux-headers.sh
        sudo dpkg -i build/linux-libc-dev-riscv32-cross_*.deb

    - name: Build glibc
      run: |
        bash scripts/build-glibc.sh
        ls -la build/libc6*.deb
        sudo dpkg -i build/libc6-riscv32-cross_*_all.deb build/libc6-dev-riscv32-cross_*_all.deb build/libc6-dbg-riscv32-cross_*_all.deb

    - name: Build libxcrypt
      run: |
        bash scripts/build-libxcrypt.sh
        sudo dpkg -i build/libcrypt1-riscv32-cross_*.deb build/libcrypt-dev-riscv32-cross_*.deb

    - name: Build libunistring
      run: |
        bash scripts/build-libunistring.sh
        sudo dpkg -i build/libunistring5-riscv32-cross_*.deb

    # - name: Build libidn2
    #   run: |
    #     bash scripts/build-libidn2.sh
    #     sudo dpkg -i build/libidn2-0-riscv32-cross_*.deb

    # - name: Build zlib
    #   run: |
    #     bash scripts/build-zlib.sh
    #     sudo dpkg -i build/zlib1g-riscv32-cross_*.deb build/zlib1g-dev-riscv32-cross_*.deb

    # - name: Build mbedtls
    #   run: |
    #     bash scripts/build-mbedtls.sh
    #     sudo dpkg -i build/libmbedcrypto7-riscv32-cross_*.deb build/libmbedx509-1-riscv32-cross_*.deb build/libmbedtls14-riscv32-cross_*.deb build/libmbedtls-dev-riscv32-cross_*.deb

    - name: List generated packages
      run: |
        ls -lh build/*.deb

    - name: Upload packages as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: riscv32-cross-packages
        path: build/*.deb
        retention-days: 90

    - name: Create package list
      if: github.event_name == 'release'
      run: |
        cd build
        sha256sum *.deb > SHA256SUMS
        cat SHA256SUMS

    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/*.deb
          build/SHA256SUMS
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
