name: Build RISC-V 32-bit Cross Libraries

on:
  workflow_dispatch:
  push:
    branches:
      - libs

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 240  # 4 hours max
    strategy:
      matrix:
        variant:
          - { abi: ilp32, arch: rv32imac, name: "soft-float" }
          - { abi: ilp32d, arch: rv32gc, name: "double-precision" }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo sed -i 's/^\(\s*Types:\s*\)deb\(.*\)/\1deb deb-src\2/' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            dpkg-dev \
            devscripts \
            debhelper \
            cmake \
            pkg-config \
            wget \
            curl

      - name: Download and install RISC-V 32-bit toolchain for ${{ matrix.variant.abi }}
        run: |
          # Download the toolchain package for this variant
          gh run download 18507769659 \
            -R pguyot/crossbuild-essential-riscv32 \
            --name riscv32-gnu-toolchain-${{ matrix.variant.abi }}-2025.09.28

          # Install the toolchain
          sudo dpkg -i riscv32-gnu-toolchain-${{ matrix.variant.abi }}_2025.09.28_amd64.deb

          # Add to PATH for all subsequent steps
          echo "/opt/riscv32-${{ matrix.variant.abi }}/bin" >> $GITHUB_PATH

          # Verify installation
          /opt/riscv32-${{ matrix.variant.abi }}/bin/riscv32-unknown-linux-gnu-gcc --version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build glibc 2.39 packages:riscv32 (${{ matrix.variant.abi }})
        run: |
          bash scripts/build-glibc.sh ${{ matrix.variant.abi }} ${{ matrix.variant.arch }}

      - name: List glibc 2.39 packages:riscv32 (${{ matrix.variant.abi }})
        run: |
          echo "=== glibc packages ==="
          ls -lh build/*.deb
          for deb in build/libc6-${{ matrix.variant.abi }}*.deb build/libc6-dev-${{ matrix.variant.abi }}*.deb build/libc6-dbg-${{ matrix.variant.abi }}*.deb; do
            [ -f "$deb" ] && dpkg-deb -c "$deb"
          done

      - name: Build zlib1g and zlib1g-dev:riscv32 (${{ matrix.variant.abi }})
        run: |
          bash scripts/build-zlib.sh ${{ matrix.variant.abi }} ${{ matrix.variant.arch }}

      - name: List zlib1g and zlib1g-dev:riscv32 (${{ matrix.variant.abi }})
        run: |
          echo "=== zlib packages ==="
          ls -lh build/*.deb
          for deb in build/*.deb; do
            [ -f "$deb" ] && dpkg-deb -c "$deb"
          done

      - name: Build libmbedtls libraries and dev package:riscv32 (${{ matrix.variant.abi }})
        run: |
          bash scripts/build-mbedtls.sh ${{ matrix.variant.abi }} ${{ matrix.variant.arch }}

      - name: List libmbedtls libraries and dev package:riscv32 (${{ matrix.variant.abi }})
        run: |
          echo "=== mbedtls packages ==="
          ls -lh build/*.deb
          for deb in build/*.deb; do
            [ -f "$deb" ] && dpkg-deb -c "$deb"
          done

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: riscv32-cross-libs-${{ matrix.variant.abi }}
          path: build/*.deb
          retention-days: 90
