name: Build RISC-V 32-bit Cross Libraries

on:
  workflow_dispatch:
  push:
    branches:
      - libs

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 240  # 4 hours max

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            dpkg-dev \
            devscripts \
            debhelper \
            cmake \
            pkg-config \
            wget \
            curl

      - name: Download and install RISC-V 32-bit toolchain
        run: |
          # Download the toolchain package from the specific run
          gh run download 18452360237 \
            -R pguyot/crossbuild-essential-riscv32 \
            --name riscv32-gnu-toolchain-multilib-2025.09.28

          # Install the toolchain
          sudo dpkg -i riscv32-gnu-toolchain-multilib_2025.09.28_amd64.deb

          # Add to PATH for all subsequent steps
          echo "/opt/riscv32/bin" >> $GITHUB_PATH

          # Verify installation
          riscv32-linux-gnu-gcc --version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build libc6-dbg:riscv32
        run: bash scripts/build-libc6-dbg.sh

      - name: Build zlib1g and zlib1g-dev:riscv32
        run: bash scripts/build-zlib-multiarch.sh

      - name: Build libmbedtls libraries and dev package:riscv32
        run: bash scripts/build-mbedtls-multiarch.sh

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: riscv32-cross-libs
          path: build/*.deb
          retention-days: 90
